import Navbar from "@/components/widgets/navbar";
import type { Metadata } from "next";
import "swiper/css";
import "./globals.css";
import Footer from "@/components/widgets/footer";
import { Box } from "@mui/material";
import MobileHeader from "@/components/widgets/mobile-header";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Digixito",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>
      <body>
        <Box sx={{ display: { lg: "block", xs: "block" } }}>
          <Navbar />
        </Box>
        {/* <Box sx={{ display: { lg: "none", xs: "block" } }}>
          <MobileHeader />
        </Box> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
