import Footer from "@/components/widgets/footer";
import Navbar from "@/components/widgets/navbar";
import { Box } from "@mui/material";
import type { Metadata } from "next";
import "swiper/css";
import "./globals.css";
import SmokeyCursor from "@/components/lightswind/smokey-cursor";
import "aos/dist/aos.css";
import "animate.css";

export const metadata: Metadata = {
  title: "Digixito",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
    shortcut: "/favicon.png",
    apple: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Box sx={{ display: { lg: "block", xs: "block" } }}>
          <Navbar />
        </Box>

        {/* <SmokeyCursor /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
